//
//  LEPMessageHeader.h
//  etPanKit
//
//  Created by DINH Viêt Hoà on 31/01/10.
//  Copyright 2010 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>

@class LEPAddress;

/**
 An LEPMessageHeader object is a container for the 'envelope' of all messages that are either sent or recieved.  It provides a standard location for all address-related variables, subject, dates, and IDs.
 */

@interface LEPMessageHeader : NSObject <NSCoding> {
	NSString * _messageID;
	NSArray * /* NSString */ _references;
	NSArray * /* NSString */ _inReplyTo;
    LEPAddress * _sender;
	LEPAddress * _from;
	NSArray * /* LEPAddress */ _to;
	NSArray * /* LEPAddress */ _cc;
	NSArray * /* LEPAddress */ _bcc;
	NSArray * /* LEPAddress */ _replyTo;
	NSString * _subject;
    NSDate * _date;
	NSDate * _internalDate;
	NSString * _userAgent;
}

/** A unique ID that is generated by the email client on a per-email basis.
 @see NSString(LEPUUID)
 @warning *IMPORTANT* This property cannot be nil.  If it is, behavior may be undefined in a different email client.
 */
@property (nonatomic, retain) NSString * messageID;
@property (nonatomic, copy) NSArray * /* NSString */ references;
@property (nonatomic, copy) NSArray * /* NSString */ inReplyTo;

@property (nonatomic, retain) NSDate * date;
@property (nonatomic, retain) NSDate * internalDate;

@property (nonatomic, retain) LEPAddress * sender;
@property (nonatomic, retain) LEPAddress * from;
@property (nonatomic, copy) NSArray * /* LEPAddress */ to;
@property (nonatomic, copy) NSArray * /* LEPAddress */ cc;
@property (nonatomic, copy) NSArray * /* LEPAddress */ bcc;
@property (nonatomic, copy) NSArray * /* LEPAddress */ replyTo;
@property (nonatomic, retain) NSString * subject;
@property (nonatomic, retain, readonly) NSString * extractedSubject;
@property (nonatomic, retain, readonly) NSString * partialExtractedSubject;

-(NSString*)datedMessageID;

/** A user agent describing the software that sent the message.
 
 The userAgent is stored in the message under the X-Mailer header field.  The X-Mailer mail header field is used to describe the software used in sending the email.  If you send an email using Outlook, you'll find an X-Mailer header in your outgoing email that indicates that Outlook sent it, and the version.  Likewise, the X-Mailer header for emails sent by the Chilkat email component will indicate that "Chilkat Software" was the mailer. You may change it so that the name of your application is contained in X-Mailer.
 
 */
@property (nonatomic, copy) NSString * userAgent;

@end
